#pragma once
// Common extensions synonyms
// Renderbuffer
#define GL_RENDERBUFFER          GL_RENDERBUFFER_EXT
#define GL_STENCIL_INDEX1        GL_STENCIL_INDEX1_EXT
#define GL_STENCIL_INDEX4        GL_STENCIL_INDEX4_EXT
#define GL_STENCIL_INDEX8        GL_STENCIL_INDEX8_EXT
#define GL_STENCIL_INDEX16       GL_STENCIL_INDEX16_EXT
//# define GL_DEPTH_COMPONENT24     GL_DEPTH_COMPONENT24_EXT
// Framebuffer
#define GL_FRAMEBUFFER           GL_FRAMEBUFFER_EXT
#define GL_COLOR_ATTACHMENT0     GL_COLOR_ATTACHMENT0_EXT
#define GL_DEPTH_ATTACHMENT      GL_DEPTH_ATTACHMENT_EXT
#define GL_STENCIL_ATTACHMENT    GL_STENCIL_ATTACHMENT_EXT
#define GL_FRAMEBUFFER_COMPLETE  GL_FRAMEBUFFER_COMPLETE_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT           GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT   GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_DUPLICATE_ATTACHMENT GL_FRAMEBUFFER_INCOMPLETE_DUPLICATE_ATTACHMENT_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS  GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_FORMATS     GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER_EXT
#define GL_FRAMEBUFFER_UNSUPPORTED  GL_FRAMEBUFFER_UNSUPPORTED_EXT
#define GL_FRAMEBUFFER_STATUS_ERROR GL_FRAMEBUFFER_STATUS_ERROR_EXT
// Limits
#define GL_MAX_COLOR_ATTACHMENTS GL_MAX_COLOR_ATTACHMENTS_EXT
#define GL_MAX_RENDERBUFFER_SIZE GL_MAX_RENDERBUFFER_SIZE_EXT
// Multisampling
//#define GL_MULTISAMPLE GL_MULTISAMPLE_ARB
